repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: git@github.com:mercadolibre/fury_websec-git-hooks.git
    rev: v1.0.3
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]